### ISSUE TITLE
Grid lines in image when using Hybrid Model

### ISSUE THREAD

**Issue by xion824** [deepskydetail/AstroSharp#14]
First time running into this issue. When I use Hybrid Model, I end up getting grid lines in my image. But only in Hybrid. I've found that HM does a really good job with reducing noise compared to the other models, so I tend to use this one. Any idea what could be causing this? Love the program. It really does an excellent job. Image attached.
![Processed_2024-04-23_ASHM](https://github.com/deepskydetail/AstroSharp/assets/5812053/a938dc02-d5dd-450d-a7e9-b870f1c83a84)

**Comment by deepskydetail** [comment]
Thanks for the feedback, and great image! I think I know what is going on.
It sharpens the image sections at a time. Then it denoises those sections
immediately afterward. The fact that the whole image hasn't been denoised
yet, makes it so that where the sections meet, sharp distinctions are made.
I'll see if I can make a fix. It might take a bit. One workaround might be
to change the chunk size and run it again, then average the two images
together in Gimp or Photoshop.

In theory, running the sharpening, then running the denoiser separately
should give you the same results (as long as you use the same
aggressiveness slider for both). That should be another workaround. Hope
that helps, and let me know if you have any other questions!

**Comment by xion824** [comment]
Separating out the sharpening and denoise did help a bit. Thank you for that advice. It may have also had something to do with that specific image as well. I reprocessed a few other sets, and they were fine.
